apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2019-11-07T11:30:04Z"
  name: carts-canary
  resourceVersion: "33536"
  selfLink: /api/v1/namespaces/sockshop-staging/services/carts
  uid: f1cced54-0151-11ea-af0b-42010a9c0198
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: carts
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
